name: "fuzz"
on:
  workflow_dispatch:
  schedule:
    - cron: "22 13 * * 1,3"

permissions:
  contents: write
  pull-requests: write

jobs:
  list:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "stable"
      - id: list
        uses: shogo82148/actions-go-fuzz/list@2caf0a4e74459a82e94234a021500539451f0e00 # v1.2.4
    outputs:
      fuzz-tests: ${{steps.list.outputs.fuzz-tests}}

  fuzz:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    needs: list
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.list.outputs.fuzz-tests)}}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "stable"
      - uses: shogo82148/actions-go-fuzz/run@7887fe2495518ecf2504c6ebdede1764dec11018 # v1.2.3
        with:
          packages: ${{ matrix.package }}
          fuzz-regexp: ${{ matrix.func }}
          fuzz-time: "355m"
